version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    image: backend
    build: ./backend
    container_name: donzoom
    environment:
      TZ: Asia/Seoul
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis  # Redis 의존성 추가

  redis:
    image: redis:6.2  # Redis 이미지 지정
    container_name: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"  # Redis 기본 포트
    volumes:
      - ./redis_data:/data  # Redis 데이터 저장소 설정
